[package]

name = "flatestream"
version = "0.0.1"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
build = "make"

[[bin]]
name = "reader"
test = false
doc = false

[[bin]]
name = "writer"
test = false
doc = false
